# Generated by Django 5.0.6 on 2024-06-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_cta",
            field=models.CharField(
                blank=True,
                help_text="Texto para mostrar como Call to Action",
                max_length=255,
                verbose_name="Hero CTA",
            ),
        ),
    ]
